[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ascii-image"
version = "0.1.0"
description = "A package to convert images to ascii art."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pillow>=11.0.0",
    "Flask>=2.3.0",
    "google-cloud-storage>=3.0.0",
]

[project.scripts]
ascii-image = "ascii_image.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
include-package-data = true

[[tool.mypy.overrides]]
module = ["pandas", "pandas.*"]
ignore_missing_imports = true
